#!/bin/bash

# echo "Total Parameters: $#"

# UTIL_SCRIPT=$(find . -name "utils" -type f -exec readlink -f {} \;)
# source "$UTIL_SCRIPT"

if (("$#" < 1)); then
  echo "syntax: ./decompress <base-dir>"
  echo "usage: ./decompress /data/backups/mysql/base"
  exit 1
fi

# Positional Parameters
DECOMPRESS_BASE_DIR="$1"

# All Compressed files have the extension ".lz4" by default
COMPRESSED_FILES=$(find "${DECOMPRESS_BASE_DIR}" -iname "*\.lz4")

for i in $COMPRESSED_FILES;
do
  lz4 -vdm < $i > $(dirname $i)/$(basename $i .lz4) && rm $i;
done
