#!/bin/bash

# echo "Total Parameters: $#"

if (("$#" < 2)); then
  echo "syntax: ./decrypt <base-dir> <keyfile-path>"
  echo "usage: ./decrypt /data/backups/mysql/base /data/backups/keyfile"
  exit 1
fi

# Positional Parameters
DECRYPT_BASE_DIR="$1"
KEY_FILE_PATH="$2"

# All Encrypted files have the extension ".xbcrypt"
ENCRYPTED_FILES=$(find "${DECRYPT_BASE_DIR}" -iname "*\.xbcrypt")

for i in $ENCRYPTED_FILES;
do
  xbcrypt -d -v --encrypt-key-file=$KEY_FILE_PATH --encrypt-algo=AES256 < $i > $(dirname $i)/$(basename $i .xbcrypt) && rm $i;
done
