#!/bin/bash

BASE_DIR="$1"
KEYFILE_PATH="$2"

XBSTREAM_SEARCH_PATTERN="*.xbstream"
XBSTREAM_FILES=$(ls "${BASE_DIR}" | grep -E "${XBSTREAM_SEARCH_PATTERN}")
# echo "file: $XBSTREAM_FILE"

ALL_XBSTREAM_FILES=$(echo "${XBSTREAM_FILES}" | wc -l)

if (( "${ALL_XBSTREAM_FILES}" <= 0 )); then
  echo "Error: No stream files ('.xbstream') found. Please check backup logs for more information."
  exit 1
elif (( "${ALL_XBSTREAM_FILES}" > 1 )); then
  echo "Error: More than one stream file found. Only a single stream file ('.xbstream') allowed to be in a single directory."
  exit 1
fi

if [[ $(echo "${XBSTREAM_FILES}" | wc -l) -eq 1 ]]; then
  echo "Found a stream file: ${XBSTREAM_FILES}."
  RESTORE_DIR="${BASE_DIR}/restore"
  mkdir -p "${RESTORE_DIR}"
  
  echo "Extracting the stream..."
  xbstream -x -C "./stream_extract/" < "./base/dump.xbstream" 
fi



# xtrabackup \
# --decrypt \
# --encrypt-key-file="${KEYFILE_PATH}" \
# --decompress \
# --target-dir="${BASE_DIR}"
